### ISSUE TITLE
Using python 3.7.4 after modified np.load(image_path +'CLEVR_dict.npy' , allow_pickle=True, encoding='bytes').item()

### ISSUE THREAD

**Issue by CyberFork** [yitong91/StoryGAN#11]
Traceback (most recent call last):                                                                                        File "main_clevr.py", line 99, in <module>                                                                                algo.train(imageloader, storyloader, testloader)                                                                      File "P:\StoryGAN\code\trainer.py", line 100, in train                                                                    netG, netD_im, netD_st = self.load_networks()                                                                         File "P:\StoryGAN\code\trainer.py", line 49, in load_networks                                                             netG = StoryGAN(self.video_len)                                                                                       File "P:\StoryGAN\code\model.py", line 222, in __init__                                                                   self.define_module()                                                                                                  File "P:\StoryGAN\code\model.py", line 234, in define_module                                                              nn.Linear(ninput, ngf * 4 * 4 / 2, bias=False),                                                                       File "P:\Python37\lib\site-packages\torch\nn\modules\linear.py", line 72, in __init__                                     self.weight = Parameter(torch.Tensor(out_features, in_features))                                                    TypeError: new() received an invalid combination of arguments - got (float, int), but expected one of:                   * (torch.device device)                                                                                                 * (torch.Storage storage)                                                                                               * (Tensor other)                                                                                                        * (tuple of ints size, torch.device device)                                                                                  didn't match because some of the arguments have invalid types: (float, int)                                        * (object data, torch.device device)                                                                                         didn't match because some of the arguments have invalid types: (float, int)

**Comment by yitong91** [comment]
The current .npy is saved by python2. There should be some compatibility issue. The easiest solution may be using python 2 to open and see the data structure. Then generate a new .npy file from python 3.

**Comment by martinezhermes** [comment]
**DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.**
